spring:
  datasource:
      url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=quizlet
      username: sa
      password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    jpa:
      hibernate:
        ddl-auto: none



